language: python
python:
    - "3.6"

branches:
  only:
  - master

before_install:
    - sudo apt-get install expect -y
    - sudo pip install setuptools

install:
    - sudo python3 setup.py install

deploy:
    script: deploy_pypi.sh